spring:
  application:
    name: eurka-client-one
    cloud:
      config:
        discovery:
          enabled: true
          service-id: configserver
        label: master
        name: eurka-client-one   #多模块获取git配置中心属性，这里需要些该模块名称
        profile: dev
        uri: http://localhost:9001/

# eureka
eureka:
  instance:
    hostname: localhost
    # 心跳间隔，即服务续约间隔时间，隔这个时间会主动心跳一次（缺省为30s）设置为5s上报一次心跳
    leaseRenewalIntervalInSeconds: 4
    # 设置服务过期时间配置,超过这个时间没有接收到心跳（缺省为90s）EurekaServer就会将这个实例剔除 一般为3个心跳周期
    leaseExpirationDurationInSeconds: 12
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8762


management:
  endpoints:
    web:
      exposure:
        include: refresh,info
