spring:
  application:
    name: eurka-feign

# eureka ×¢²áÖĞĞÄÅäÖÃ
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765